-- Script tạo bảng cho hệ thống The Bang Coffee (Oracle SQL)

-- 1. Bảng Nguyên Liệu
CREATE TABLE NGUYEN_LIEU (
    MaNL VARCHAR2(20) PRIMARY KEY,
    TenNL NVARCHAR2(100) NOT NULL,
    DVT_CoBan NVARCHAR2(20),
    SoLuongTon NUMBER(10, 2) DEFAULT 0
);

-- 2. Bảng Sản Phẩm
CREATE TABLE SAN_PHAM (
    MaSP VARCHAR2(20) PRIMARY KEY,
    TenSP NVARCHAR2(100) NOT NULL
);

-- 3. Bảng Biến Thể Sản Phẩm (Size)
CREATE TABLE BIEN_THE_SP (
    MaBienThe VARCHAR2(20) PRIMARY KEY,
    MaSP VARCHAR2(20) REFERENCES SAN_PHAM(MaSP),
    TenSize NVARCHAR2(20),
    GiaBan NUMBER(15, 0)
);

-- 4. Bảng Topping
CREATE TABLE TOPPING (
    MaTopping VARCHAR2(20) PRIMARY KEY,
    TenTopping NVARCHAR2(100) NOT NULL,
    GiaBan NUMBER(15, 0),
    MaNL_LienKet VARCHAR2(20) REFERENCES NGUYEN_LIEU(MaNL),
    DinhLuongHaoHut NUMBER(10, 2)
);

-- 5. Bảng Công Thức
CREATE TABLE CONG_THUC (
    MaCongThuc VARCHAR2(20) PRIMARY KEY,
    MaBienThe VARCHAR2(20) REFERENCES BIEN_THE_SP(MaBienThe),
    MaNL VARCHAR2(20) REFERENCES NGUYEN_LIEU(MaNL),
    DinhLuong NUMBER(10, 2)
);

-- 6. Bảng Hóa Đơn
CREATE TABLE HOA_DON (
    MaHD VARCHAR2(20) PRIMARY KEY,
    TongTien NUMBER(15, 0),
    TrangThai NVARCHAR2(50),
    NgayTao DATE DEFAULT SYSDATE
);

-- 7. Chi Tiết Hóa Đơn
CREATE TABLE CT_HOA_DON (
    MaCTHD VARCHAR2(20) PRIMARY KEY,
    MaHD VARCHAR2(20) REFERENCES HOA_DON(MaHD),
    MaBienThe VARCHAR2(20) REFERENCES BIEN_THE_SP(MaBienThe),
    SoLuong NUMBER(5),
    DonGia NUMBER(15, 0)
);

-- 8. Chi Tiết Topping cho từng món trong hóa đơn
CREATE TABLE CT_TOPPING (
    MaCTHD VARCHAR2(20) REFERENCES CT_HOA_DON(MaCTHD),
    MaTopping VARCHAR2(20) REFERENCES TOPPING(MaTopping),
    DonGiaTopping NUMBER(15, 0),
    PRIMARY KEY (MaCTHD, MaTopping)
);

-- 9. Bảng Phiếu Nhập Kho
CREATE TABLE PHIEU_NHAP_KHO (
    MaPN VARCHAR2(20) PRIMARY KEY,
    NgayNhap DATE DEFAULT SYSDATE,
    TongTien NUMBER(15, 0),
    GhiChu NVARCHAR2(255)
);

-- 10. Chi Tiết Phiếu Nhập Kho
CREATE TABLE CT_PHIEU_NHAP_KHO (
    MaPN VARCHAR2(20) REFERENCES PHIEU_NHAP_KHO(MaPN),
    MaNL VARCHAR2(20) REFERENCES NGUYEN_LIEU(MaNL),
    SoLuong NUMBER(10, 2),
    DonGia NUMBER(15, 0),
    TyLeQuyDoi NUMBER(10, 2) DEFAULT 1,
    ThanhTien NUMBER(15, 0),
    PRIMARY KEY (MaPN, MaNL)
);

-- 11. Sản Phẩm - Topping (Liên kết n-n)
CREATE TABLE SP_TOPPING (
    MaSP VARCHAR2(20) REFERENCES SAN_PHAM(MaSP),
    MaTopping VARCHAR2(20) REFERENCES TOPPING(MaTopping),
    PRIMARY KEY (MaSP, MaTopping)
);

-- 12. Lô Nguyên Liệu (Quản lý HSD và FEFO)
CREATE TABLE LO_NGUYEN_LIEU (
    MaLo VARCHAR2(50) PRIMARY KEY,
    MaNL VARCHAR2(20) REFERENCES NGUYEN_LIEU(MaNL),
    MaPN VARCHAR2(20) REFERENCES PHIEU_NHAP_KHO(MaPN),
    SoLuongBanDau NUMBER(15, 2),
    SoLuongConLai NUMBER(15, 2),
    DonGiaQuyDoi NUMBER(15, 2),
    HanSuDung DATE
);

-- 13. Phiếu Hủy Hàng
CREATE TABLE PHIEU_HUY_HANG (
    MaPhieuHuy VARCHAR2(20) PRIMARY KEY,
    NgayHuy DATE DEFAULT SYSDATE,
    GhiChu NVARCHAR2(255)
);

CREATE TABLE CT_PHIEU_HUY_HANG (
    MaPhieuHuy VARCHAR2(20) REFERENCES PHIEU_HUY_HANG(MaPhieuHuy),
    MaLo VARCHAR2(50) REFERENCES LO_NGUYEN_LIEU(MaLo),
    SoLuongHuy NUMBER(15, 2),
    LyDo NVARCHAR2(100),
    PRIMARY KEY (MaPhieuHuy, MaLo)
);

-- 14. Quản lý Ca Làm Việc
CREATE TABLE CA_LAM_VIEC (
    MaCa VARCHAR2(50) PRIMARY KEY,
    NhanVienTruc NVARCHAR2(100),
    ThoiGianBatDau TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianKetThuc TIMESTAMP,
    TongDoanhThu NUMBER(15, 0) DEFAULT 0,
    TrangThai NVARCHAR2(20) DEFAULT 'Đang mở' -- Đang mở, Đã chốt
);

-- Dữ liệu mẫu (Sample Data)
INSERT INTO NGUYEN_LIEU VALUES ('NL01', 'Hạt Cà Phê', 'Gram', 10000);
INSERT INTO NGUYEN_LIEU VALUES ('NL02', 'Sữa Đặc', 'ml', 5000);
INSERT INTO NGUYEN_LIEU VALUES ('NL03', 'Trân Châu Đen', 'Gram', 2000);

INSERT INTO SAN_PHAM VALUES ('SP01', 'Cà Phê Sữa');
INSERT INTO BIEN_THE_SP VALUES ('BT01', 'SP01', 'M', 25000);
INSERT INTO BIEN_THE_SP VALUES ('BT02', 'SP01', 'L', 35000);

INSERT INTO TOPPING VALUES ('TP01', 'Trân Châu', 5000, 'NL03', 30);

INSERT INTO CONG_THUC VALUES ('CT01', 'BT01', 'NL01', 20);
INSERT INTO CONG_THUC VALUES ('CT02', 'BT01', 'NL02', 30);

COMMIT;
